enum actionTypes {
  PERSON_ADD = 'ADD_PERSON',
  PERSON_DELETE = 'DELETE_PERSON',
  PERSON_REQUST_BEGIN = 'PERSON_REQUST_BEGIN',
  PERSON_REQUEST_SUCCESS = 'PERSON_REQUEST_SUCCESS',
  PERSON_REQUEST_ERROR = 'PERSON_REQUEST_ERROR',
}

export default actionTypes;
